position: 2
token: env(token)
username: env(username)

help: |
  <b>Помощь по игре "FutureWars"</b>

  <b>Цель игры</b>: остаться единственной выжившей командой
  <b>Атака</b>: атака снимает 1хп у цели и тратит 1 ед. заряда лазера
  <b>Защита</b>: блокирует N единиц урона нанесенного вам. Если вы заблокировали весь урон, вы получаете 2 ед. энергии лазера. Иначе - 1
  <b>Защита флага</b>: блокирует N единиц урона, нанесенного флагу. При потере флага вся команда проигрывает!
  <b>Зарядка лазера/щита</b>: восстановление текущего заряда лазера/щита на 3 ед. Максимальный заряд - 5
  <b>Уворот</b>: 60% шанс увернуться от всех атак, доступно каждые 5 ходов
  <b>Создание клона</b>: создает вашего клона, с теми же LP, SP как и у вас, и повторяющего ваши ходы. Умирает через 3 хода. При вашей смерти так же умирает.
  <b>AFK</b>: за пропуск 2х ходов подряд, вы умрете
  <b>Инфа по монеткам:</b>Вы получаете x монеток при:
  - убийстве игрока, где x = монетки игрока / кол-во атаковавших в этот ход + 1
  - убийстве флага, x = 10 / кол-во атаковавших + 3
  - убийстве клона, x = 1
  - убийстве CoinMonster, x = рандом(5, 10) / кол-во атаковавших + 1.
  Ваш клон передаст вам свои монетки перед следующим ходом
  КоинМонстры появляются в начале игры и каждые 5 ходов, макс. кол-во монстров - 5

  <b>В планах</b>:
  Туррели, внутриигровой магазин с предметами (расходники)

  Идея игры взята у <a href="tg://user?id=441399484">Пасюка</a>, с его <a href="tg://user?id=703334403">офигительнейшего бота</a>
  Канал обновлений - https://t.me/FutureWarsUpdates
  Основная идея игры - почти никакого рандома, за результат игры отвечает не шанс совершения действия, а скилл игрока
